var tuerBase = require('../../model/base'),
restify = require('restify'),
EventProxy = require('eventproxy').EventProxy,
util = require('../../lib/util'),
querystring = require('querystring');
exports.user= function(){};
exports.edit= function(){};
exports.save= function(){};
exports.del= function(){};
